name: C/C++ CI

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - name: apt update
      run: sudo apt update
    - name: add-apt-repository
      run: sudo add-apt-repository ppa:vriviere/ppa -y
    - name: apt
      run: sudo apt install ninja-build lua5.1 pasmo libz80ex-dev flex libbsd-dev libreadline-dev bison binutils-arm-linux-gnueabihf binutils-i686-linux-gnu binutils-powerpc-linux-gnu gcc-m68k-atari-mint qemu-user gpp 64tass libfl-dev nasm
    - name: make
      run: make NINJAFLAGS=-k1

