name: C/C++ CI

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: apt update
      run: sudo apt update
    - name: add-apt-repository
      run: sudo add-apt-repository ppa:vriviere/ppa -y
    - name: apt
      run: sudo apt install moreutils lua5.1 libz80ex-dev flex libbsd-dev libreadline-dev bison binutils-arm-linux-gnueabihf binutils-i686-linux-gnu binutils-powerpc-linux-gnu binutils-m68k-atari-mint binutils-m68k-linux-gnu qemu-user gpp 64tass libfl-dev nasm
    - name: make
      run: make -j$(nproc)

